# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

from PyInstaller.utils.hooks import collect_all
from pathlib import Path

psycopg_datas, psycopg_binaries, psycopg_hiddenimports = collect_all("psycopg")

a = Analysis(
    ['server.py'],
    pathex=[],
    binaries=[
        *psycopg_binaries,
    ],
    datas=[
        *psycopg_datas,
        ('alembic.ini', '.'),
        ('alembic/env.py', 'alembic'),
        *[(str(path), 'alembic/versions') for path in Path('alembic/versions').glob('*.py')],
    ],
    hiddenimports=[
        'main',
        'psycopg',
        'httpx',
        'httpx._config',
        'httpx._multidict',
        'httpx._models',
        'httpx._types',
        'httpx._utils',
        *psycopg_hiddenimports,
        'app.api.router',
        'app.api.reports',
        'app.services.final_menu_service',
        'app.api.health',
        'app.api.auth',
        'app.api.settings',
        'app.api.users',
        'app.api.orders',
        'app.api.payments',
        'app.api.printing',
        'app.api.categories',
        'app.api.products',
        'app.api.price_options',
        'app.api.addons',
        'app.api.manual_price_presets',
        'app.api.product_images',
        'app.api.delivery_workers',
        'app.api.admin_config',
        'app.api.cancellation',
        'app.models',
        'app.database.connection',
        'app.core.config',
        'app.core.security',
        'app.services.auth_service',
        'app.services.order_service',
        'app.services.payment_service',
        'app.services.print_service',
        'app.services.catalog_service',
        'app.services.settings_service',
        'app.services.telegram_outbox_service',
        'app.telegram.client',
        'app.telegram.worker',
        'app.telegram.runtime',
        'app.telegram.events',
        'app.telegram.message_builder',
        'app.seed.runner',
        'app.printer.interface',
        'app.printer.receipt_builder',
        'alembic.env',
        'PySide6.QtWebEngineCore',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='RestaurantServer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
